[theme]
primaryColor="#4CAF50"  # Calming green for primary buttons and highlights (suggesting health, stability)
backgroundColor="#FFFFFF"  # Clean white background for readability
secondaryBackgroundColor="#F0F2F6"  # Light gray for subtle separation of sections
textColor="#31333F"  # Dark gray text for clarity and readability
font="sans serif"  # Clean, modern, and easy-to-read sans serif font
